### ISSUE TITLE
USERAUTH fail

### ISSUE THREAD

**Issue by ndeloof** [cloudbees/cloudbees-eclipse#7]
I've installed a fresh new Eclipse Kepler (Java developer dist) + EGit + CloudBees plugin
setup credentials (validate successfully) and tried to use a clickstart - I always get the wizard to fail with "USERAUTH fail" error.

Plugin is performing connectivity validations at clickstart list to prevent usability issue when user moves forward with the clickstart but then it turns out it fails to clone the repository. It's good to have it before user has entered more information for the clickstart invoke.

But yeah "USERAUTH fail" is not that user friendly error reporting.

**Comment by ahtik** [comment]
Should no longer happen.
