### ISSUE TITLE
"Run locally" start SDK in interactive mode

### ISSUE THREAD

**Issue by ndeloof** [cloudbees/cloudbees-eclipse#8]
console ask me to enter email, but fail to create configuration :

    Updating Bees SDK. This may take a while
    ...
    You have not created a CloudBees configuration profile, let's create one now...

That's odd as I entered my cloudbees account in Eclipse preference. This anyway fails even if I enter valid account credentials 

    ERROR: Cannot create configuration

**Comment by ahtik** [comment]
SDK is no longer supported.
